import { IEvent } from "../IEvent";
import { USAState } from "@prisma/client";

export const eventListTest: IEvent[] = [
    {
        id: 1,
        name: "Coachella 2025",
        state: USAState.CALIFORNIA,
        city: "Coachella Valley",
        zipCode: "9324",
        street: "Monroe St.",
        externalNumber: 534,
        internalNumber: 341,
        public: true,
        done: false,
        startDate: new Date(2025, 4, 25, 15, 0),
        endDate: new Date(2025, 4, 28, 17, 0),
        maxUsers: 40
    },
    {
        id: 2,
        name: "Coachella 2025",
        state: USAState.CALIFORNIA,
        city: "Coachella Valley",
        zipCode: "9324",
        street: "Monroe St.",
        externalNumber: 534,
        internalNumber: 341,
        public: false,
        done: false,
        startDate: new Date(2025, 4, 25, 11, 20),
        endDate: new Date(2025, 4, 28, 17, 0),
        maxUsers: 40
    },
    {
        id: 3,
        name: "Coachella 2025",
        state: USAState.CALIFORNIA,
        city: "Coachella Valley",
        zipCode: "9324",
        street: "Monroe St.",
        externalNumber: 534,
        internalNumber: 341,
        public: true,
        done: false,
        startDate: new Date(2025, 4, 25, 15, 30),
        endDate: new Date(2025, 4, 28, 17, 0),
        maxUsers: 40
    },
    {
        id: 4,
        name: "Coachella 2025",
        state: USAState.CALIFORNIA,
        city: "Coachella Valley",
        zipCode: "9324",
        street: "Monroe St.",
        externalNumber: 534,
        internalNumber: 341,
        public: false,
        done: false,
        startDate: new Date(2025, 4, 25, 15, 30),
        endDate: new Date(2025, 4, 28, 17, 0),
        maxUsers: 40
    },
    {
        id: 5,
        name: "Coachella 2025",
        state: USAState.CALIFORNIA,
        city: "Coachella Valley",
        zipCode: "9324",
        street: "Monroe St.",
        externalNumber: 534,
        internalNumber: 341,
        public: false,
        done: false,
        startDate: new Date(2025, 4, 25, 15, 30),
        endDate: new Date(2025, 4, 28, 17, 0),
        maxUsers: 40
    },
    {
        id: 6,
        name: "Coachella 2025",
        state: USAState.CALIFORNIA,
        city: "Coachella Valley",
        zipCode: "9324",
        street: "Monroe St.",
        externalNumber: 534,
        internalNumber: 341,
        public: false,
        done: false,
        startDate: new Date(2025, 4, 25, 15, 30),
        endDate: new Date(2025, 4, 28, 17, 0),
        maxUsers: 40
    },
    {
        id: 7,
        name: "Coachella 2025",
        state: USAState.CALIFORNIA,
        city: "Coachella Valley",
        zipCode: "9324",
        street: "Monroe St.",
        externalNumber: 534,
        internalNumber: 341,
        public: false,
        done: false,
        startDate: new Date(2025, 4, 25, 15, 30),
        endDate: new Date(2025, 4, 28, 17, 0),
        maxUsers: 40
    },
    {
        id: 8,
        name: "Coachella 2025",
        state: USAState.CALIFORNIA,
        city: "Coachella Valley",
        zipCode: "9324",
        street: "Monroe St.",
        externalNumber: 534,
        internalNumber: 341,
        public: false,
        done: false,
        startDate: new Date(2025, 4, 25, 15, 30),
        endDate: new Date(2025, 4, 28, 17, 0),
        maxUsers: 40
    },
    {
        id: 9,
        name: "Coachella 2025",
        state: USAState.CALIFORNIA,
        city: "Coachella Valley",
        zipCode: "9324",
        street: "Monroe St.",
        externalNumber: 534,
        internalNumber: 341,
        public: false,
        done: false,
        startDate: new Date(2025, 4, 25, 15, 30),
        endDate: new Date(2025, 4, 28, 17, 0),
        maxUsers: 40
    },
    {
        id: 10,
        name: "Coachella 2025",
        state: USAState.CALIFORNIA,
        city: "Coachella Valley",
        zipCode: "9324",
        street: "Monroe St.",
        externalNumber: 534,
        internalNumber: 341,
        public: false,
        done: false,
        startDate: new Date(2025, 4, 25, 15, 30),
        endDate: new Date(2025, 4, 28, 17, 0),
        maxUsers: 40
    },
    {
        id: 11,
        name: "Coachella 2025",
        state: USAState.CALIFORNIA,
        city: "Coachella Valley",
        zipCode: "9324",
        street: "Monroe St.",
        externalNumber: 534,
        internalNumber: 341,
        public: false,
        done: false,
        startDate: new Date(2025, 4, 25, 15, 30),
        endDate: new Date(2025, 4, 28, 17, 0),
        maxUsers: 40
    },
    {
        id: 12,
        name: "Coachella 2025",
        state: USAState.CALIFORNIA,
        city: "Coachella Valley",
        zipCode: "9324",
        street: "Monroe St.",
        externalNumber: 534,
        internalNumber: 341,
        public: false,
        done: false,
        startDate: new Date(2025, 4, 25, 15, 30),
        endDate: new Date(2025, 4, 28, 17, 0),
        maxUsers: 40
    },
    {
        id: 13,
        name: "Coachella 2025",
        state: USAState.CALIFORNIA,
        city: "Coachella Valley",
        zipCode: "9324",
        street: "Monroe St.",
        externalNumber: 534,
        internalNumber: 341,
        public: false,
        done: false,
        startDate: new Date(2025, 4, 25, 15, 30),
        endDate: new Date(2025, 4, 28, 17, 0),
        maxUsers: 40
    },
    {
        id: 14,
        name: "Coachella 2025",
        state: USAState.CALIFORNIA,
        city: "Coachella Valley",
        zipCode: "9324",
        street: "Monroe St.",
        externalNumber: 534,
        internalNumber: 341,
        public: false,
        done: false,
        startDate: new Date(2025, 4, 25, 15, 30),
        endDate: new Date(2025, 4, 28, 17, 0),
        maxUsers: 40
    },
    {
        id: 15,
        name: "Coachella 2025",
        state: USAState.CALIFORNIA,
        city: "Coachella Valley",
        zipCode: "9324",
        street: "Monroe St.",
        externalNumber: 534,
        internalNumber: 341,
        public: false,
        done: false,
        startDate: new Date(2025, 4, 25, 15, 30),
        endDate: new Date(2025, 4, 28, 17, 0),
        maxUsers: 40
    },
    {
        id: 16,
        name: "Coachella 2025",
        state: USAState.CALIFORNIA,
        city: "Coachella Valley",
        zipCode: "9324",
        street: "Monroe St.",
        externalNumber: 534,
        internalNumber: 341,
        public: false,
        done: false,
        startDate: new Date(2025, 4, 25, 15, 30),
        endDate: new Date(2025, 4, 28, 17, 0),
        maxUsers: 40
    },
    {
        id: 17,
        name: "Coachella 2025",
        state: USAState.CALIFORNIA,
        city: "Coachella Valley",
        zipCode: "9324",
        street: "Monroe St.",
        externalNumber: 534,
        internalNumber: 341,
        public: false,
        done: false,
        startDate: new Date(2025, 4, 25, 15, 30),
        endDate: new Date(2025, 4, 28, 17, 0),
        maxUsers: 40
    },
    {
        id: 18,
        name: "Coachella 2025",
        state: USAState.CALIFORNIA,
        city: "Coachella Valley",
        zipCode: "9324",
        street: "Monroe St.",
        externalNumber: 534,
        internalNumber: 341,
        public: false,
        done: false,
        startDate: new Date(2025, 4, 25, 15, 30),
        endDate: new Date(2025, 4, 28, 17, 0),
        maxUsers: 40
    },
]